name: Publish Package to npmjs

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for generating OIDC token to authenticate with npm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Upgrade npm to latest
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm install

      - name: Publish to npm with Provenance (Trusted Publishing)
        run: npm publish --provenance
